### ISSUE TITLE
[MDCOutlinedTextField] background color

### ISSUE THREAD

**Issue by kristinamartinkevich** [material-components/material-components-ios#10021]
<img width="355" alt="Screenshot 2020-06-14 at 22 05 12" src="https://user-images.githubusercontent.com/31727202/84601745-29037100-ae8b-11ea-88c9-f19132662ffd.png">

is there a way to change the background color only of the part that's limited by the outline? 
right now its set as
`email.backgroundColor = .blue`

**Comment by andrewoverton** [comment]
Is this an `MDCTextField` with an `MDCTextInputControllerOutlined`, rather than an `MDCOutlinedTextField`? It looks like an `MDCTextField`. In any case, there is no way to set just the region within the outline to be a specific color on an `MDCOutlinedTextField`. I believe the same is true for `MDCTextField`. This is not supported because it doesn't really work nicely with the floating label. When the label is floating there is a break in the outline, and it's unclear what should happen with the proposed background color then. Should it just stop at the border even though there's no outline keeping it in?
