### ISSUE TITLE
[TextFields] MDCOutlinedTextField - different sizes depending on labelBehavior property

### ISSUE THREAD

**Issue by brennobemoura** [material-components/material-components-ios#10046]
> For usage questions: ask on [Stack  Overflow](https://stackoverflow.com/questions/tagged/material-components+ios).

I'm using the new MDCOutlinedTextField, but after some update, the TextField change frame layout depending on labelBehavior property. The `.floats` has 60 of height and the `.disappears` has 41.

## Reproduction steps

1. Set labelBehavior equal to `.disappears`

## Expected behavior

The TextField with disappears label behavior should have the same frame size as floats label behavior.

## Actual behavior

The TextField has 41 of height.

## Platform (please complete the following information)

 - Device: iPhone 11
 - OS: iOS 14
 - Xcode 12

## Additional context

None.

**Comment by andrewoverton** [comment]
Hello, that is correct, a recent change made it so that the default text field height is smaller when there is no floating label. There is a new property called `preferredContainerHeight` that you can now set if you want the text field to be taller than that. I'm going to close this issue for now but feel free to ask any additional questions!
