### ISSUE TITLE
MDCOutlinedTextField Height Issue

### ISSUE THREAD

**Issue by ErAshu** [material-components/material-components-ios#10127]
How to reduce the padding between the stroke and text field. 

Actually, I want to reduce the whole height.

<img width="354" alt="Screenshot 2020-11-19 at 6 11 35 PM" src="https://user-images.githubusercontent.com/4178384/99667821-ede91780-2a92-11eb-91c1-1cc6968b79bb.png">

**Comment by andrewoverton** [comment]
In order to reduce the spacing between individual elements, and thus the height of the text field overall, I need to expose a `density` property. There's been a lot of discussion about exposing density in https://github.com/material-components/material-components-ios/issues/9860, so let's continue tracking this feature request there. You can subscribe to that one and I'll close this one for the sake of reducing duplication. Thanks!
