### ISSUE TITLE
[FlexibleHeader] Can't find property `canAlwaysExpandToMaximumHeight`

### ISSUE THREAD

**Issue by ManuelEMR** [material-components/material-components-ios#10137]
MDCFlexibleHeaderView' has no member 'canAlwaysExpandToMaximumHeight'

I'm trying to set `canAlwaysExpandToMaximumHeight` to my headerView, and I'm unable to set it.

I'm using swift and importing as:
`import MaterialComponents.MaterialFlexibleHeader`

**Comment by andrewoverton** [comment]
Hi @ManuelEMR , I think in order to use this property you need to add the [`FlexibleHeader+CanAlwaysExpandToMaximumHeight`](https://github.com/material-components/material-components-ios/blob/develop/components/FlexibleHeader/src/MDCFlexibleHeaderView.m#L90) to your Podfile. I'm going to close this issue but please re-open if this doesn't fix your issue. Thanks!
