### ISSUE TITLE
Installed MaterialComponents having 124 warnings!

### ISSUE THREAD

**Issue by DanGerHOGGISH** [material-components/material-components-ios#10201]
- [x] Measure internal usage of the API.
- [x] Create a GitHub issue.
- [ ] Write a migration guide.
- [ ] Add a comment to the API indicating that it will be deprecated.
- [ ] Determine a schedule for the API deletion.
- [ ] Announce that the API will be deprecated
- [ ] After the deprecation date, annotate the API as deprecated.
- [ ] After the deletion date, re-evaluate usage of the API.
- [ ] Delete the API and migration guide.

**Comment by DanGerHOGGISH** [comment]
![image](https://user-images.githubusercontent.com/67454411/117919693-e3ebf700-b306-11eb-8346-ffe508fcdef9.png)
Good morning. I installed MaterialComponents via Cocoapods and having 124 warning issues because of the implementing deprecated class. What do you suggest to do in order to get rid of these issues?

**Comment by andrewoverton** [comment]
Hi @DanGerHOGGISH, I would recommend installing individual subspecs for the components you want, as opposed to installing the whole library. This would entail putting `pod MaterialComponents/Buttons`, for example, in your Podfile, instead of `pod MaterialComponents`. This may not eliminate warnings, but it will definitely reduce them. All the warnings in this image are from a deprecated class, so I would expect warnings to be there.

**Comment by jverkoey** [comment]
Material libraries for iOS entered maintenance mode as of July 15, 2021. Learn more at https://github.com/material-components/material-components-ios#material-components-for-ios.
