### ISSUE TITLE
Button changes title color when the button is disabled/re-enabled

### ISSUE THREAD

**Issue by Arcank** [material-components/material-components-ios#1160]
### Overview
Button changes title color when the button is disabled/re-enabled.

[Demo-button-issue.mov.zip](https://github.com/material-components/material-components-ios/files/716580/Demo-button-issue.mov.zip)

### Reproduction steps
- Patch https://github.com/Arcank/material-components-ios/pull/1.
- Open Catalog > Buttons > Demo.
=> Note the enabled flat button title color is grey.
- Tap a button (it spawns a form sheet that is automatically dismissed after 2 seconds).
=> The enabled flat button gets disabled in the background, then reenabled when the page is dismissed. After the dismissal, the enabled flat button title color is blue.

### Version number
f1e6a3d

### Operating system and device
iPad, iPhone Plus
iOS 10 (below not tested)

**Comment by willlarche** [comment]
Should it have been blue all along?

**Comment by Arcank** [comment]
No because the initial grey is set on purpose:
https://github.com/material-components/material-components-ios/blob/develop/components/Buttons/examples/ButtonsTypicalUse.m#L59

What happens is that:
1. The ambient tint color is blue. But since the customTitleColor is set, the tint is not used.
2. The form is presented, there is a global tint color change (tint color grey), and every view is visited with a call to tintColorDidChange:
https://github.com/material-components/material-components-ios/blob/develop/components/Buttons/src/MDCButton.m#L315
It overrides the custom title color to the grey tint color.
3. The form is dismissed, the same visit is made and the tint color of the button is changed again to blue.

So the customTitleColor is unset as soon as the tintColor is changed (manually or by the system).

**Comment by Arcank** [comment]
Simple enough, it's due to 85dd5428. Should we revert?

**Comment by Arcank** [comment]
Note that setting `underlyingColorHint` to white is unsufficient (I need to check in Catalog).

**Comment by Arcank** [comment]
@samsymons for feedback. Thanks!

**Comment by samsymons** [comment]
Interesting — I'll investigate this some more in a few hours and either submit a fix, or submit a revert for those changes. Thanks for finding that @Arcank!

**Comment by Arcank** [comment]
Hi Sam, any new development? Thanks!

**Comment by samsymons** [comment]
@Arcank Yes, I'm very sorry for the delay there!

I believe the core issue here is that the `tintColor` is not set initially — from the [documentation](https://developer.apple.com/reference/uikit/uiview/1622467-tintcolor):

> If the system cannot find a nondefault color in the hierarchy, this property’s value is a system-defined color instead.

I tested a fix which sets the `tintColor` when the user sets the custom title color, which partially fixed the issue. This caused the title color to fade out when the modal is presented due to the OS fading the tint color automatically, which can be fixed with `self.tintAdjustmentMode = UIViewTintAdjustmentModeNormal`.

With the adjustment mode changed and the `tintColor` updated when the custom title color is set, the color no longer changed when the universal tint color is modified by the OS. Also, if the `tintColor` itself is set now, then that change persists through modal presentation.

@Arcank If that change sounds good to you, I can open a PR — otherwise I will open a PR removing the `tintColorDidChange` implementation. 😄

**Comment by Arcank** [comment]
How come the adjustment mode is not `.Normal` by default? I don't see it set anywhere in MDC: https://github.com/material-components/material-components-ios/search?utf8=%E2%9C%93&q=tintAdjustmentMode&type=Code

I think it's a nice touch to have this adjustment mode. But it should act on both the title and the background color.
When there is a non-default color, how do you compute/retrieve the correct disabled color?

I guess that setting explicitly a tint color should automatically disable the feature.

Finally, conflating tintColor and customTitleColor seems fitting for a flat button, but what about a raised button? For such a button, I'd see more the background color tied to the tintColor than the title color. I think that we could implement different behaviors in the subclasses instead of the base class.

What do you think?

**Comment by willlarche** [comment]
Is this still unresolved?

**Comment by Arcank** [comment]
Technically, this is resolved with @samsymons revert.
