### ISSUE TITLE
Dialogs are not modal?

### ISSUE THREAD

**Issue by qiangyu** [material-components/material-components-ios#1183]
### Overview

The alerts presented by MDCAlertController is not modal

### Reproduction steps

I copied the sample code from README.md:
```
      let alertController = MDCAlertController(title: "error", message: "error")
      let action = MDCAlertAction(title:"OK") { (action) in print("OK") }
      alertController.addAction(action)
      present(alertController, animated: true, completion: {})
```

The dialog presented is not modal. Touch anywhere on the screen then the dialog disappears

### Version number
19.04 and 20.1.0

### Operating system and device
iPhone 6S with iOS 10.1.1

**Comment by ianegordon** [comment]
Hi Qiang,

We have implemented our AlertControllers to the Material spec:
https://material.io/guidelines/components/dialogs.html#dialogs-behavior

"Dialogs can be dismissed by touching/clicking outside of a dialog. Alternatively, dialog behavior can be overridden so that users must explicitly choose one of the actions."

You can set the dismissOnBackgroundTap property on the presentation controller to NO to get your desired effect.

I have added an example to Catalog : Dialogs : AlertController demonstrating the above.  It should land soon.
https://github.com/material-components/material-components-ios/pull/1184

Let me know if you have further questions.
