### ISSUE TITLE
MDCThumbTrack doesn't mask track when interpolate colors is NO

### ISSUE THREAD

**Issue by chuckhays** [material-components/material-components-ios#1201]
### Overview
Due to change in https://github.com/material-components/material-components-ios/commit/d908571869c9be7e67509a063010f087847062ed

When interpolateOnOffColors is NO, a separate layer is still used for the on track color, but this layer no longer has a rounded rect mask, it was eliminated in the above change.

### Reproduction steps
 Create an instance of MDCThumbTrack, set interpolateOnOffColors to NO, set stops to 2 (use it as a switch), observe rectangular track when in on state.

### Related issues
 #566

**Comment by ajsecord** [comment]
Thanks for the bug report! However, Thumbtrack is a private component only used in the implementation of Slider and is otherwise unsupported. It looks like `interpolateOnOffColors` is now vestigial and should be removed. (For context, Thumbtrack was once used in more components than just Slider.)

I filed #1202 to remove the `interpolateOnOffColors` to reduce the maintenance cost.
