### ISSUE TITLE
[Typography] testIsLargeForContrastRation fails on 8.4

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#1291]
### Overview
This test fails on this line:

```objc
  XCTAssertTrue(
      [fontLoader isLargeForContrastRatios:[fontLoader mediumFontOfSize:largeIfBoldSize]]);
```

### Reproduction steps
Run in 8. I used iPhone 6 Plus 8.4 - Fails
Run in 9+. I used iPhone 6 Plus 9.3 - Passes

**Comment by ianegordon** [comment]
We are defining any font with a weight greater than 0.23 (UIFontWeightMedium) as 'BOLD'.
On 8.x Asking for a systemFontAtSize:15 weight:Medium returns a font with a weight of 0.2, which is below our BOLD cutoff.

Looking.

**Comment by ianegordon** [comment]
iOS8 handles Medium font requests by create a normal weight font of a specific font face instead of a medium font weight of a general font family.  Therefore we can't assume the weight is valid on iOS8.

Possible workaround options:

- If font.fontName is "HelveticaNeue-Medium" return YES.
  Minimal Impact
  Only handles iOS8 system font medium issue.

- If font.fontName ends in "-Medium" return YES.
  Requires font to be named according to a standard that may not actually be standard
  Handles 'all' fonts so named.
  Will fail in cases where the name of a font includes -Medium, but the encoded weight is not.

**Comment by ianegordon** [comment]
I'm leaning toward the first / simpler fix, but I wanted to hear any strong opinions.

**Comment by willlarche** [comment]
First sounds good. Does that .2 have an acceptable contrast ratio?

**Comment by ianegordon** [comment]
I don't know that we can verify contrast ratios without much deeper inspection of the fonts.

PR with first / simpler implementation is out for review #1292.
