### ISSUE TITLE
[Dialogs] PresentationController: Callback for dismissOnBackgroundTap?

### ISSUE THREAD

**Issue by thkeen** [material-components/material-components-ios#1455]
Currently there's no callback if users tap on background to dismiss the dialog, in which some cases it forces us to disable this feature because there's no way to notify the UI to update properly.

https://github.com/material-components/material-components-ios/blob/develop/components/Dialogs/src/MDCDialogPresentationController.h#L47

---
#### Internal data
- Associated internal bug: [b/117179681](http://b/117179681)

**Comment by ianegordon** [comment]
Investigate adding a delegate protocol.

**Comment by ianegordon** [comment]
Proposal based on UIPopoverPresentationControllerDelegate:

@protocol MDCDialogPresentationControllerDelegate
@optional
- (BOOL)dialogPresentationControllerShouldDismissDialog:
- (void)dialogPresentationControllerDidDismissDialog:
@end

**Comment by ianegordon** [comment]
We need to identify the accessibility affects of this change.
If shouldDismiss returns NO, how will that affect the VoiceOver behavior for the back gesture.
We should identify and likely match Apple's handling of VO for popover presented views.

**Comment by romoore** [comment]
I'm not sure that there is much of an accessibility component to this feature request. If a user not using VoiceOver cannot dismiss a dialog, then I think it's OK for a VoiceOver user to have the same experience.

**Comment by thkeen** [comment]
SGTM

**Comment by skgopt** [comment]
Hi, the submitted fix for this isn't really useful for cases where the callback is specific to the alert. Could we simply get a way to directly set a completion on the MDCAlertController or the MDCDialogPresentationController?

**Comment by romoore** [comment]
@skgopt Can you please open a new Issue with a code snippet showing how the delegate callbacks aren't working for your use case?  It seems like any code that is presenting an AlertController would be able to create a delegate object that handles the callback.  This is similar to passing a completion block, but the delegate also allows coordination for multiple alerts/presentations (if desired).

**Comment by andrewoverton** [comment]
@skgopt have you tried accessing the `presentedViewController` property of the MDCDialogPresentationController parameter in the delegate method? I think it should allow you to distinguish between multiple alerts and handle dismissals differently depending on the alert.

**Comment by skgopt** [comment]
To my view, the problem with this delegate design is that I have to somewhere manually manage the retention of delegate objects. MDCAlertController can not be subclassed to make it its own delegate, nor store any alert-specific variables that may be used in the delegate method. I would like some way to store all of the elements needed for the alert follow up action, and have their lifetimes be tied to the lifetime of the alert.

For instance:

```
@implementation MyViewController
...
- (void)presentLoadErrorAlertWithMessage:(NSString *)message {
  MDCAlertController *controller = [MDCAlertController alertControllerWithTitle:kLoadErrorTitle 
                                                                                                                       message:message];
  controller.mdc_dialogPresentationController.dialogPresentationControllerDelegate = self;
  [self presentViewController:controller
                                        animated:YES
                                 completionQueue:dispatch_get_main_queue()
                                      completion:nil];
}

// Every single view controller that wants to present alerts has to have this, or own and manage a 
// series of objects that implement this. Clients that abstract alert controller creation and 
// presentation out into a separate service will have to rethink their architecture, and bring some of
// that functionality back into the individual presenting controllers.
#pragma mark - MDCDialogPresentationControllerDelegate

// All required services for all follow-up actions must be kept alive and available, instead of being 
// captured with the alert.
// And this if-else ladder to retroactively infer which alert was presented is also required.
- (void)dialogPresentationControllerDidDismissDialog:
     (MDCDialogPresentationController *)dialogPresentationController {
  id presentedController = dialogPresentationController.presentedViewController;
  NSAssert([presentedController isKindOfClass:[MDCAlertController class]], 
                    @"Return value is not of type MDCAlertController.");
  MDCAlertController *controller= (MDCAlertController *)presentedController;
  if ([controller.title isEqualToString(kLoadErrorTitle)]) {
    // maybe test message or other properties to retroactively infer context and do something
    // with available services
  } else if (... for all other kinds of alerts being presented from this class ...) {
    // try to use possibly non-unique combinations of property values on MDCAlertController to 
    // somehow either retrieve or reconstruct state and then use available services to take action.
  }
}
...
@end
```

If I am missing something really fundamental, and there is an easier way to do this. Please correct my assumptions or oversights.

**Comment by ianegordon** [comment]
Hi @skgopt !  Thank you for the detailed request.  I believe I have an understanding of your concerns:
Since an alertController doesn't capture any state aside from it's initial setup, the dismissal don't have the context necessary to easily handle the response.

For context, MDCAlertController is intended to be a drop-in replacement for UIAlertController.  Because of that, we are *very* hesitant to expand the API past what Apple provides.  For further functionality we point clients toward rolling their own view controller and using MDCDialogPresentationController.

MDCAlertController does not use blocks, because UIAlertController doesn't use them.  In order to add the functionality for the dismiss handler, we again took our inspiration from UIKit, UIPopoverPresentationControllerDelegate to be specific.

While I see the utility of having the dismissal block attached to the alert, it violates the encapsulation of the responder chain.  To put it another way, when you click outside the alert to dismiss it, you are explicitly *not* interacting with the alert, so the alert shouldn't be involved in the handling of those events.  Of the top of my head, I can't think of an example in UIKit that behaves in that fashion.  Do you know of one?

Based on that, I'm not currently (yet?) convinced that we should make this change.  If you'd like, I'd be happy to discuss further on VC.  Feel free to put something on my calendar.

**Comment by ianegordon** [comment]
Closing pending further offline discussion with @skgopt .  May be re-opened in the future.
