### ISSUE TITLE
Why aren't color theme APIs extensions to the existing APIs?

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#1539]
In digging in to the components I've noticed that each component has its own color theming extension spec. I was surprised to see that each color theme introduces its own `Themer` object. Given that we own the components, I was surprised that we weren't using a named extension to add the APIs we need here. Is there a reason why we didn't take this approach?

The reason I assumed we'd take an extension approach is that it would allow us to expose APIs on the existing objects. This would improve discoverability of the APIs and make auto-completion suggest the API to users of instances of the components.

An example:

```objc
@interface MDCPageControl (ColorTheming)
- (void)applyColorScheme:(NSObject<MDCColorScheme> *)colorScheme;
@end

[pageControl applyColorScheme:colorScheme];
```

**Comment by ajsecord** [comment]
We're separating theming from the class itself—it's a general pattern. @randallli is the themer write up ready to share?

**Comment by jverkoey** [comment]
Yep! I get that's what's going on - my question stems from asking why we choose to do this instead of extending a class that we own.

**Comment by ajsecord** [comment]
Very long discussion. Let's let Randall chime in. :)

**Comment by jverkoey** [comment]
Haha alright :)

**Comment by randallli** [comment]
We didn't want to create a strong dependency on a colorScheme object/protocol for each and every component. 
As for why it is a separate class instead of a class category:
It may be just an implementation detail for why. Our mutator pattern methods have been easier to reason about when they are static methods. We currently prefer them to not have state. However I didn't consider a mutator as a class category.
