### ISSUE TITLE
titleView not center aligned for MDCAppBar

### ISSUE THREAD

**Issue by somberImp** [material-components/material-components-ios#1650]
When setting a titleView, the titleView is not centered within the view, but rather within the remaining space (if left/right buttons are present)

Repro:
  UIImageView *customTitleView = [[UIImageView alloc]initWithFrame:...
  customTitleView.backgroundColor = [UIColor redColor];
  self.navigationItem.titleView = customTitleView;

Screenshot of UINavigationBar vs MDCAppBar's behavior.

<img width="948" alt="screen shot 2017-07-13 at 10 31 06 am" src="https://user-images.githubusercontent.com/2817234/28233042-f42f528a-68a8-11e7-8ef0-32d3ad5159a3.png">

Note that the same imageview was set to the titleView of these two bars, and that AppBar is not centering the view within the view as a whole.

**Comment by romoore** [comment]
Should be fixed by #1721

**Comment by jverkoey** [comment]
This behavior appears to still be occurring.

**Comment by AlimoRabbani** [comment]
I also had an issue with this when trying to center items in the titleView when left/right buttons are not symmetric. My workaround was to position the subviews based on the originX of the titleView, and the width of the superview of the titleView.

If this is fixed in the library and titleView always has the same left/right margins in the navigationBar frame, I'm not sure how left/right aligning content inside the titleView can work. For example: if you have 0 left buttons, 2 right buttons,  and you want to left-align the content inside the titleView.

**Comment by jverkoey** [comment]
In order to maintain existing behavior I’ll likely go with a floatingPosition API.
