### ISSUE TITLE
AppBar's button ink is the wrong color in MDCCatalog

### ISSUE THREAD

**Issue by ajsecord** [material-components/material-components-ios#1660]
MDCCatalog has mostly dark colors with a lighter colored ink. The MDCButtonBarButton in the MDCAppBar seems to still have a dark ink applied, so it is barely visible.

Example:
1. Open MDCatalog > App Bar > Demo
1. Tap and hold on the button "Right"
1. Notice that the ink is barely visible as a darker color behind the text.

**Comment by romoore** [comment]
I believe this is caused by ButtonBar not having ink.

**Comment by AlimoRabbani** [comment]
Are there any updates on this? I'm facing a similar issue because I can't customize the ink color for the button bars in MDCAppBar.

**Comment by ajsecord** [comment]
@romoore I'm not sure what you mean—the container called button bar doesn't have ink, but the buttons in it definitely do?

**Comment by romoore** [comment]
@ajsecord The buttons in ButtonBar don't seem to have Ink, I don't believe this is a bug specific to AppBar.

**Comment by AlimoRabbani** [comment]
The buttons in the ButtonBar use MDCFlatButton's default inkColor since MDCButtonBarButton inherits from it. The default inkColor is some sort of dark gray [1], so it appears there's no ink in MDCCatalog, because the app bar background is also dark gray.

One possible way to fix this is to publicly expose and inkColor property on MDCNavigationBar and pipe it all the way through to MDCAppBarButtonBarBuilder and set the inkColor on the created MDCButtonBarButton.

Another solution is to make all UIBarButtonItems passed to MDCNavigationBar implement a protocol 
that allows adding inkColor, and use that in the MDCAppBarButtonBarBuilder directly. Not sure if there's already such protocol in the library.

Please let me know what you think.

[1] https://github.com/material-components/material-components-ios/blob/218ed1ab686e369c35e2f4b1c24256008a7d1324/components/Buttons/src/MDCFlatButton.m#L32

**Comment by AlimoRabbani** [comment]
We can also use UIAppearance and set the inkColor of MDCButtonBarButton when contained in MDCNavigationBar on the client side. That fixes the immediate problem, but leads to the client making certain assumptions about the internal structure of the MDCNavigationBar. WDYT?
