### ISSUE TITLE
BottomNavigation not added to material components

### ISSUE THREAD

**Issue by farshadmb** [material-components/material-components-ios#1792]
### Overview
 [BottomNavigation](https://material.io/guidelines/components/bottom-navigation.html).

The Library does not add BottomNavigation yet.

**Comment by romoore** [comment]
Hi farshadmb! Thanks for the feedback.  I believe bottom navigation is supported by the Navigation Bar, with an example provided in [BottomNavigationBarExample.m](https://github.com/material-components/material-components-ios/blob/develop/components/Tabs/examples/BottomNavigationBarExample.m).  🤔

![simulator screen shot - iphone 5s - 2017-08-14 at 08 47 26](https://user-images.githubusercontent.com/1753199/29272244-34d520f8-80cd-11e7-9177-058a19712b5b.png)

If there are specific guidelines from the Material Design specification that you feel are missing (😓), please open Issues for them.  I'm going to resolve this issue, feel free to reopen it if I've missed something. Thanks! ☺️

**Comment by farshadmb** [comment]
@romoore you don't mention in your docs and dont use `UItabBarController`

**Comment by romoore** [comment]
Hi @farshadmb, sorry for mixing-up Navigation Bar and Tab Bar - I was looking at the variable names instead of the file path.  

Which docs are missing a reference to the Bottom Navigation?  I see the [README for Tabs](https://github.com/material-components/material-components-ios/tree/develop/components/Tabs) has a subsection titled, "Bottom navigation".  In general, I don't believe the Material Design guidelines link directly to components for each platform.  I think we have generally tried to keep the design guidelines separate from our implementation.

MDCTabBar doesn't require a UITabBarController to function, instead you provide an MDCTabBarDelegate to respond to selection events.  Is there some UITabBarController-like functionality you'd like to see added?
