### ISSUE TITLE
[Feature Request]  Implement Navigation Drawer

### ISSUE THREAD

**Issue by ilap** [material-components/material-components-ios#1803]
### Overview
This is a feature request to implement the [Navigation Draw](https://material.io/guidelines/patterns/navigation-drawer.html) pattern specified in [Material Guidelines](https://material.io/guidelines/#).

It's likely already implemented by Google as [Google Keep for iOS](https://support.google.com/keep/answer/2888240?co=GENIE.Platform%3DiOS&hl=en&oco=2) already uses that feature.

It's already implemented in [Material Components for Android](https://material.io/components/android/catalog/navigation-view/) and [Web](https://material.io/components/web/catalog/drawers/).

### Reproduction steps
- None
### Version number
 - None

### Operating system and device
- None
### Related issues
- None

**Comment by willlarche** [comment]
Hi, ilap!

Thanks for writing and being a user of MDC-iOS!

This is a common request but unfortunately one we have no current plans to fulfill.

Side panels / hamburger buttons hurt UX metrics. There are several [published](https://www.nngroup.com/articles/hamburger-menus/) UX studies on the subject. The long and the short of it is that it's hiding functionality which leads to lower feature discovery. People end up doing less in your app and not finding the stuff they need!

The preferred navigation paradigm is bottom nav which iOS implements usually via UITabBar (-Controller). We have a slightly modified version of bottom navigation in our Tabs called ["MDCTabBarViewController"](https://github.com/material-components/material-components-ios/blob/develop/components/Tabs/src/MDCTabBarViewController.h).

The [Material](https://material.io/guidelines/) designers have decided, especially for iOS, that a navigation drawer is an acceptable paradigm only for certain situations (like account switching.) So, you'll still see it in Google apps. But since it's not the best practice for general navigation, it won't be in MDC. 

Try to convince your UX designer to work on new solutions for your navigation! It is absolutely worth it to have greater user engagement. 

If you still need a side drawer, there are [many](https://cocoapods.org/?q=drawer) cocoapods out there that can help.

Thanks again for writing and consider contributing to our many other components! We'd love to have you help us with [issues](github.com/material-components/material-components-ios/issues).
