### ISSUE TITLE
[Typography] mdc_preferredFont: is returning the incorrect version of .SFUI Font Family

### ISSUE THREAD

**Issue by sigito** [material-components/material-components-ios#1805]
`[MDCTypography titleFont]` returns a _20pt_ font with font family `.SFUIDisplay-Medium`, when 
`[UIFont mdc_preferredFontForMaterialTextStyle:MDCFontTextStyleTitle]` returns `.SFUIText-Medium`. While I cannot find this anywhere officially, but according to [San Francisco display vs text / compact vs normal a brief review](http://protosketch.io/san-francisco-display-vs-text-compact-vs-normal-a-brief-review/):

> The OS will change the two fonts automagically **text is for sizes up to 19pt and display is from sizes above 19pt**. This will not be the case in design software though.

Indeed the `UIFont` family returned for _19pt_ is `.SFUIText`, and for _20pt_ - `.SFUIDisplay`.

It seems that the fix would be to cache values for _Text_ and _Display_ fonts in [UIFontDescriptor+MaterialTypography.m](https://github.com/material-components/material-components-ios/blob/develop/components/Typography/src/UIFontDescriptor%2BMaterialTypography.m#L39) and select a proper one depending on `materialTraits.pointSize`.

**Comment by ianegordon** [comment]
Hi @sigito. Good catch! Fixing this may get pulled into removing some of the font legacy code once we drop support for iOS 8 (Pre-SF), but your suggestion sounds like a good solution.

**Comment by sigito** [comment]
Does this mean we would have to wait until iOS 8 support is dropped? Is there a tracking issue or an ETA for it?

**Comment by ianegordon** [comment]
Currently there is no firm schedule on dropping iOS 8 support.
That conversation will likely not begin until iOS 11 reaches general availability.

If you are interested in getting a fix in sooner rather than later, PRs are always welcome and I would be happy to work with you to get a PR landed. If you aren't comfortable putting together a PR, let me know and I'll try and get this issue priority higher in the backlog.

Your proposed solution SGTM.  I would replace systemFontFamilyName with smallSystemFontFamilyName and largeSystemFontFamilyName, setting the UIFontDescriptorFamilyAttribute as appropriate.  I would want to verify things work as expected on iOS 8, and perhaps add unit tests to demonstrate we are returning the right family for each size.
