### ISSUE TITLE
[CollectionCells] MDCCollectionViewTextCell can not handle more than 3 lines

### ISSUE THREAD

**Issue by mpetrov** [material-components/material-components-ios#1806]
MDCCollectionViewTextCell layouts break if more than 3 lines of content are supplied. The implementation explicitly handles `numberOfAllVisibleTextLines` equal to 1, 2, and 3. Margins and icon alignment break if 4 or more lines of text are shown.

**Comment by romoore** [comment]
I believe this is expected behavior because the Material Design guidelines only define 1-, 2-, and 3-line lists.

https://material.io/guidelines/components/lists.html#lists-actions

**Comment by ajsecord** [comment]
Yes, that's right—I recommend that you make a custom cell for longer text.

**Comment by mpetrov** [comment]
Fair point. Though would it make sense to have some messaging around this? The current behavior is basically a weird undefined state.

**Comment by ajsecord** [comment]
@romoore points out that Dynamic Type might also cause similar problems, which we definitely want to support. Ideally we'd support any number of lines for robustness' sake (and document that 1-3 lines is best). 

I'm going to leave this open since there is definitely work to do here.

Thanks for the report!

**Comment by ianegordon** [comment]
Done in #4718
