### ISSUE TITLE
[FlexibleHeader] Support Safe Area

### ISSUE THREAD

**Issue by chuga** [material-components/material-components-ios#2008]
### Overview
Issues visible in the Catalog: Multiple examples have issues with the default header height (taller than expected). The Standard UINavigationBar example has issues with the positioning of the buttons and the status bar. The Configurator example has issues when Shift Behavior is enabled, as described in #1969.

#### Configurator:
![configurator](https://user-images.githubusercontent.com/4545451/30613171-1cf4566c-9d55-11e7-8a84-08d8af862b26.png)

![configurator](https://user-images.githubusercontent.com/1753199/30378711-071d83d4-98cf-11e7-9317-9e9c629b364e.png)

#### Standard UINavigationBar
![buttons](https://user-images.githubusercontent.com/1753199/30379849-cf9d67c2-98d2-11e7-94a7-2536e5252548.png)

### Version number
35.0.0

### Operating system and device
iOS 11 / iPhone X

**Comment by brianjmoore** [comment]
See also: https://github.com/material-components/material-components-ios/issues/1626

**Comment by brianjmoore** [comment]
See also: https://github.com/material-components/material-components-ios/issues/1626

**Comment by brianjmoore** [comment]
I've been doing some prototyping around this and I'd like to propose a design for fixing this:
* Add a mode to the flexible header that allows UIKit to manage content insets.
* Update documentation and designs to recommend new patterns for using MDCFlexibleHeader 

# Give inset control to UIKit

Currently, the tracked scroll view's content inset is based partially on the maximum height of the header. This is accomplished by manual content inset adjustment on the tracked scroll view by MDCFlexibleHeaderView. This adjustment really does not play well with iOS 11's automatic adjustment and we shouldn't fight it.

The main change here is that we should add a mode to MDCFlexibleHeader that allows this adjustment to be mostly or completely turned off so UIKit can safely automatically adjust content insets. I am not an expert on MDCFlexibleHeader's subtleties, but it is pretty fastidious about bookkeeping and I think adding a new well-defined behavior here should be possible. I was able to get a working prototype by just commenting out various adjustments.

# Update patterns

After this change, the recommended way to adjust content insets on tracked scroll views would be to set additionalSafeAreaInsets on the view controller that owns the header view and rely on UIKit to do the rest. This requires a small shift in how all flexible header clients manage the header: Instead of the header's maximum (and minimum) height being determined directly by the owning view controller, they would be determined indirectly using safe area insets.

The shape of the new pattern would be:
* A view controller owning a flexible header wants the header's maximum height to be H points taller than the safe area's top inset. (Or some other reversible function of the safe area size)
* On init/load, the owning view controller:
  * Sets its own additionalSafeAreaInsets to (H, 0, 0, 0)
  * Sets the header's max height to a H (just as a consistent default, this may not be critical)

* On viewSafeAreaInsetsDidChange, the owning view controller:
  * Sets the header's max height to safeAreaInsets.top (because the safe area has already incorporated the desired header height)
  * Updates the header's minimum height by calculating relative to the safe area minus the additional insets (safeAreaInsets.top - H)

# Summary

The overall concept is to make a small change to the data flow so we can hand inset control to UIKit:

Previously, the owning VC updated the header's maximumHeight, and the header updated the scroll view's contentInset.

    OwningVC -> maximumHeight -[MDCFlexibleHeaderView]-> contentInset

In this proposal, the owning VC updates its safe area based on how tall it wants a header to be, UIKit updates the scroll view's contentInset automatically, and the owning VC updates the header's maximumHeight on safeAreaInsetsDidChange.

    OwningVC -> safeAreaInsets -[safeAreaInsetsDidChange]-> maximumHeight
    OwningVC -> safeAreaInsets -[UIKit]-> contentInset

**Comment by ianegordon** [comment]
Hi @jverkoey, do you have any thoughts or recommendations?

**Comment by jverkoey** [comment]
@brianjmoore's proposal looks really solid. I'm happy to help review any PR/CL - please be sure to tag me on the change.

**Comment by jverkoey** [comment]
Some thoughts/questions:

- Does status bar shifting make sense on the X?
- How well will the proposal work with horizontal pagers and changing the tracking scroll view?

**Comment by chuga** [comment]
Hey @brianjmoore, thanks for looking into this. I've been playing with it today, and I came to similar conclusions. My proposed solution though was going to let MDCFlexibleHeaderView itself react to changes to safeAreaInsets. Why would we leave that to the clients to do?

**Comment by brianjmoore** [comment]
Agreed, this should be hidden from clients as much as a possible. Happy to be an early adopter and test out API designs in a real app (complete with the aforementioned horizontal pagers)!

**Comment by popzkk** [comment]
Small note on the first comment. Isn't the default minimum height "shorter" than expected? Seeing [0], the default minimum height includes the status bar height, which is 20 for normal iPhones and 44 for iPhone X. So the default minimum height should increase 24 for iPhone X? For me it works well if I manually add 24 to this default value.

[0]: https://github.com/material-components/material-components-ios/blob/3f5b770f2c72e8347f22dccff3ad1deb4ad047cc/components/FlexibleHeader/src/MDCFlexibleHeaderView.m#L28
