### ISSUE TITLE
[Tabs] Support Safe Area

### ISSUE THREAD

**Issue by chuga** [material-components/material-components-ios#2012]
### Overview
Visible issues in the Catalog:
Even though this component has been partially fixed already, it still needs some work. When used as a bottom nav, the tab bar should extend to the bottom of the screen (like UITabBar does).

![tabBar](https://user-images.githubusercontent.com/4545451/30614188-943caa82-9d58-11e7-9e90-6f337f431e16.png)

### Version number
35.0.0

### Operating system and device
iOS 11 / iPhone X

**Comment by csilv** [comment]
Note that in addition to adjusting the height for the bottom inset, it will be necessary for MDCTabItemBar to account for the scrollView's adjustedContentInset when calculating the layouts. Currently in landscape orientation on iPhone X, the tabbar will exhibit scrolling behavior because the content is the full width of the device (812pt), but the scrollview's adjustedContentInset causes the contents to scroll horizontally.

**Comment by chuga** [comment]
Not fully closed yet, as we have https://github.com/material-components/material-components-ios/issues/2302 still open. Whoever is using an MDCTabBar needs to change its frame to account for SafeAreaInsets. Top priority should be to fix it in MDCTabBarViewController.

**Comment by malkabani** [comment]
Hi
How to set tab width?
I need to set all tabs are equal width.

**Comment by romoore** [comment]
Hi @malkabani . Thanks for using MDC-iOS. :) To set all of the tabs in an MDCTabBar to equal width, you can set the alignment to [`MDCTabBarAlignmentJustified`](https://github.com/material-components/material-components-ios/blob/develop/components/Tabs/src/MDCTabBarAlignment.h#L28)  and all of the tabs will be equally sized so that they all fit within the view bounds.  These are referred to as [Fixed Tabs in the Material Design guidelines](https://material.io/guidelines/components/tabs.html#tabs-types-of-tabs).  Hope that helps!

**Comment by Charliekenney23** [comment]
Are you guys accepting PRs for this?

**Comment by romoore** [comment]
Adding @jmdetloff  who is assigned to #2302, the remaining work for this issue.

**Comment by romoore** [comment]
@Charliekenney23 Yes, we are  always happy to review Pull Requests for any open issue. Thanks for asking!

**Comment by jverkoey** [comment]
We are encouraging use of https://github.com/material-components/material-components-ios/tree/develop/components/BottomNavigation instead of Tabs on the bottom of the screen. Marking this issue as Obsolete as a result.
