### ISSUE TITLE
[TextFields] Make multiline placeholders work in multi-line

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#2115]
Add test. If functionality is missing, add it too.

**Comment by sigito** [comment]
Hi @willlarche, unfortunately, `MDCMultilineTextField` has no support for a multiline placeholder. `numberOfLines` property on the placeholder label is not set by the text field.
How do you see the placeholder should work? Should it affect the size of the field? How should it behave when `floatingEnabledDefault` is `YES`?

**Comment by willlarche** [comment]
Closing as duplicate of #2268

**Comment by ShivaniBajaj9** [comment]
Is there a text area functionality with floating placeholder on the border in MDC?

**Comment by romoore** [comment]
At the moment, no. I believe Material Text Field Text Areas and Multi-line Fields do not float the placeholder the way Text Fields Single-line Fields do.

https://material.io/design/components/text-fields.html#input-types

[Multi-line helper/error text is an open issue](https://github.com/material-components/material-components-ios/issues/5762) since they were allowed by the guidelines after MDC Text Fields were initially written.
