### ISSUE TITLE
[FlexibleHeader] Set additionalSafeAreaInsets in the parent VC

### ISSUE THREAD

**Issue by chuga** [material-components/material-components-ios#2471]
We currently only update the topLayoutGuide. For the safeAreaLayoutGuide to work as expected we need to set the additionalSafeAreaInsets in the parent view controller of the flexible header.

---
https://www.pivotaltracker.com/story/show/156806665

**Comment by chuga** [comment]
Any thoughts on this @jverkoey @ianegordon?

**Comment by jverkoey** [comment]
Have we built a proof of concept yet? Seems worth exploring if it means better support for autolayout.

**Comment by chuga** [comment]
Nope, not yet.

**Comment by DonnaLea** [comment]
I added just two lines to the MDCFlexibleHeaderViewController.m and got it to work as I expected. I can share this as a PR, but it may need more adjustments given I don't know the full scope of MDCFlexibleHeaderViewController.

**Comment by ianegordon** [comment]
SGTM.  @DonnaLea (Heya Donna!) can you open a pull request so we can take a look?

**Comment by DonnaLea** [comment]
Hey Ian @ianegordon ! My delay in doing this is that my change seems to cause the MDCCatalog to go in an endless loop due to what I think is some code that happens in MDCCatalogControllerComponents.viewSafeAreaInsetsDidChange()
So it's definitely not a final solution, but it worked in my project and thought it might have been a good base start, but maybe not due to the endless loop. I just haven't had the time to really delve into it, sorry. If you'd still like me to send something through I can.

**Comment by ianegordon** [comment]
Even if it's not 100%  (or even 50%), PRs are always welcome.  I've created a feature-additionalsafearea branch.  We can open PRs against that for review / discussion without worrying about sending catalog into an endless loop.
I expect we will need to duplicate this code / functionality across a few of our components.
