### ISSUE TITLE
[HeaderView] [iOS 11] Adding scrollView as MDCFlexibleHeaderView's trackingScrollView results in extra contentInset

### ISSUE THREAD

**Issue by shingzhao** [material-components/material-components-ios#2610]
When adding a collectionView as subview and setting MDCAppBar's trackingScrollView to the collectionView on iOS 11, collectionView will have extra contentInset. 

The blue area is the extra contentInset.
1. iPhone X
![image](https://user-images.githubusercontent.com/26732599/33650939-dd7ce8ea-da18-11e7-98e5-93bf977919a7.png)
2. iPhone 8 Plus
![image](https://user-images.githubusercontent.com/26732599/33650946-e514d478-da18-11e7-914e-bb83cd35ff72.png)
Same issue for iPhone 8 as well

Reproduction steps
1. Set up MDCAppBar as usual. 
2. Add collectionView as UIViewController view's subview.
3. appBar.headerViewController.headerView.trackingScrollView = collectionView

Version number
41.0.0

Operating system and device
iOS 11
iPhone X
iPhone 8 Plus
iPhone 8

**Comment by chuga** [comment]
@shingzhao Could you publish this example as a branch somewhere to help debug it?

**Comment by shingzhao** [comment]
https://github.com/shingzhao/FlexibleHeaderInset

**Comment by chuga** [comment]
Thanks, Shing.

You're missing step two from the tracking scroll view setup guide: https://github.com/material-components/material-components-ios/tree/2a966822308c5fb2416081480ebf59a5734f1b66/components/FlexibleHeader#tracking-a-scroll-view

You basically need to forward the UIScrollViewDelegate methods so that the FlexibleHeader can react to the Safe Area changes. Note that for your particular use case, it might be better to add the AppBar to the DetailViewController directly, and not have ListViewController at all. That way you won't need to create a DetailViewControllerDelegate to forward those methods.

Also, you could just set  `detailViewController.collectionView?.contentInsetAdjustmentBehavior = .never` and forget about it, but you'd lose the extra inset at the bottom for the Home indicator. You could add it yourself though.

Let me know if you have more questions!
