### ISSUE TITLE
CocoaPods spec should split components from "extensions"

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#2696]
As it currently stands, if someone depends on `MaterialComponents/SomeComponentName`, they will pull in both the component and all of its theming/mutator/etc... extensions. This should not be the case.

To clean this up, we need to pull the extension targets out to their own node of the podspec spec tree.

**Comment by yarneo** [comment]
From reading the issue, I understand we want to reach a place where `pod 'MaterialComponents/<Component>` will provide us the component without the extensions, rather than having to issue 'MaterialComponents/<Component>/Component ?

If so, what about having two separate subspecs for each component, i.e.: MaterialComponents/ActivityIndicator & MaterialComponents/ActivityIndicator+Extensions. 

Does that seem reasonable?

**Comment by jverkoey** [comment]
That seems reasonable to me. I wonder if we’d want to have separate targets for each of the extension types?

@randallli thoughts?

**Comment by yarneo** [comment]
solution now merged into develop
