### ISSUE TITLE
Wrong vertical alignment of bar buttons in MDCAppBar when using custom height

### ISSUE THREAD

**Issue by AlimoRabbani** [material-components/material-components-ios#2793]
When using MDCAppBar with a custom minimumHeight set on the MDCFlexibleHeaderView, bar buttons have incorrect vertical alignment because the MDCNavigationBar still uses the default height of 56. The button bar is added to the MDCNavigationBar, which has a height of 56. The buttons are later vertically aligned to be in the middle.

This is because sizeThatFits: on MDCNavigationBar uses a hardcoded value.

**Comment by yarneo** [comment]
Hey @AlimoRabbani thanks for writing this in. Just want to make sure where you expect the bar buttons to be and where they are in practice. I tried using a minimumHeight and saw that the buttons stay on top near the status bar, were you hoping they would be centered vertically? If you have a screenshot to show that would be great!

**Comment by AlimoRabbani** [comment]
Yeah with a minimum and maximum height lower than 56, it moves closer to the top.

I was hoping it'd stay centered, but that may not make sense for cases where the height is >56. So maybe it should have a fixed distance from the top when it's >=56, and centered when it's <56.

**Comment by yarneo** [comment]
Hey @AlimoRabbani , unfortunately it seems like this problem is a bit more elaborate than changing the sizeToFit.

From my findings it seems that the minimum and maximum height properties don't always take into respect the status bar height (so their height include it). Also if we were to change the centering of the buttons we would need to do that for the title as well, which has also hardcoded values for its insets, and a pretty complex way of calculating its placement.

One possible way to go is to just have a `MIN(size.height, intrinsicContentSize.height)` in both the `sizeThatFits` in MDCNavigationBar.m and MDCButtonBar.m, but that would have the button dynamically change placement depending on the size changes of the navigationBar which might not be a wanted behavior.

 I will keep this issue open in the meanwhile but will not be able to get to push a quick fix in my current availability.
