### ISSUE TITLE
[BottomNavigation] backgroundColor UIAppearance is disabled

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#2832]
### Overview
The `init` method for BottomNavigation disabled UIAppearance on its `backgroundColor` property by assigning a value to the setter. This prevents clients from theming it via UIAppearance.

### Reproduction steps
1. Create a `setBackgroundColor:` method in MDCBottomNavigationBar.m with a breakpoint
1. Set the `backgroundColor` property via UIAppearance
1. Watch the breakpoint

### Version number
44.3.0

### Operating system and device
Any/All

**Comment by ianegordon** [comment]
I believe we will need to expose our own property that gets wired into backgroundColor.  Since we don't have access to the _ivar, the property will disable UIAppearance.

Apple also has to workaround this issue.  See UIToolBar having a barTintColor property "To tint the bar's background, please use -barTintColor." even though backgroundColor exists.
