### ISSUE TITLE
[kokoro] Kokoro build script fails locally due to expected iOS simulator versions

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3129]
### Overview
Our kokoro script is now insisting on specific iOS simulator versions to be installed on developer machines. Previously, it would use whatever version was available locally.

```bash
xctestrunner.shared.ios_errors.IllegalArgumentError: The simulator os version 11.0 is not supported. Supported simulator os versions are ['8.1', '8.3', '9.3', '11.2'].
```

### Reproduction steps
```bash
./.kokoro --target components/Chips/...
```

### Version number
49.0.0

### Related issues
Change that introduced this requirement: #3117

**Comment by yarneo** [comment]
Thanks for opening this. Our Kokoro now runs on a matrix of simulators to get a fuller coverage on different devices/simulators. If you wish to be consistent with our Kokoro coverage you would need to download the additional simulators under the Components tab in your Xcode preferences. The current additional simulators needed are 8.1, 9.3, 10.3, and 11.0 (looks like you are just short of 11.0).

Having said that, it does makes sense for us to allow more loose testing if needed locally. Due to bazel's limitations however, the way we can reach this result currently is by adding an additional argument which will be in the likes of `--coverage minimal` or something of that sort.

@romoore does that work for you? @ianegordon any thoughts?

**Comment by romoore** [comment]
Ideally, I think we set up a script to identify which iOS simulators are available and select one simulator from each major iOS release.  We should also look to pick one of each device "class":

* Major iOS releases: iOS 8.x, iOS 9.x, iOS 10.x, iOS 11.x
* Device classes: 32-bit iPhone/iPod, 32-bit iPad, 64-bit iPhone/iPod, 64-bit iPad

For pre-submit and post-submit tests, missing any of these should result in a failure. Locally it should be a warning.  We can probably pass a flag like --require_all_simulators during submit tests which would be omitted locally.

**Comment by ianegordon** [comment]
Installing multiple version of Xcode on the same machine leads to badness.
Kokoro is intended to run a matrix of devices on multiple versions of Xcode.
It is *acceptable* that the kokoro runner intending to test Xcode 8 fail when Xcode 8 isn't installed.
It would be nice if the script gated based on xcrun xcodebuild -version
"Xcode 8.6 not found, skipping Sim Z"

The matrix of devices we use on Travis was intentionally chosen for breadth over devices and versions.  Kokoro simulators should match Travis Simulators.

**Comment by jverkoey** [comment]
Please re-open if this is still in issue.
