### ISSUE TITLE
[FeatureHighlight] Inform user that feature highlight has appeared

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4036]
> It would be nice to have a uniform way for informing the user that a feature promo has appeared, as alternatives like the promo title text or the highlighted view might not provide enough context. This keeps clients from exposing their accessibility strings to classes where it's not recommended, or from implementing their own announcements.
>
> Some lightly considered suggestions: 
> 1. "Introducing new feature" +  feature title text
> 2. "Highlighting new feature" + feature title text
> 3. "Try new feature" + feature title text

---

This is an internal issue. If you are a Googler, please visit [b/78646736](http://b/78646736) for more details.

**Comment by romoore** [comment]
I think one solution here is to post a `UIAccessibilityScreenChangedNotification` and point to the title as the target.  Hopefully the title/body of the Feature Highlight view provide sufficient introduction regarding why it's being targeted.  

As for the "X new feature" suggestions, I think that's a little dangerous since Feature Highlight could also be used when calling attention to an existing feature as part of a guided tutorial, walkthrough, or onboarding process. It might not be used exclusively for announcing a "new feature."

**Comment by codeman7** [comment]
@romoore Can we close this issue?

**Comment by romoore** [comment]
Yep, I think we can close this one since it would go against our internal accessibility guidelines.
