### ISSUE TITLE
[BottomSheet] Use of MDCSheetContainerViewDelegate or something relative

### ISSUE THREAD

**Issue by secret104278** [material-components/material-components-ios#4551]
## Feature Request/Suggestion

When using Bottom sheet, I need to know weather the sheet is expanded and is in full screen, so that I can make some response to my viewcontroller, that is the contentView of bottom sheet.
I have found MDCSheetContainerViewDelegate that seems to be the solution to me
```
@protocol MDCSheetContainerViewDelegate <NSObject>

- (void)sheetContainerViewDidHide:(nonnull MDCSheetContainerView *)containerView;
- (void)sheetContainerViewWillChangeState:(nonnull MDCSheetContainerView *)containerView
                               sheetState:(MDCSheetState)sheetState;

@end
```
However, I can't find a way to implement this delegate or something like that. Is there any example of using MDCSheetContainerViewDelegate or any other solution to this situation?
Thanks a lot

---
#### Internal data
- Associated internal bug: [b/117177517](http://b/117177517)

**Comment by jverkoey** [comment]
@yarneo A use case similar to what we discussed last week with respect to bottom sheets/navigation drawers. Looks like in this case there is a desire to react to bottom sheet height changes from the custom content view controller.

**Comment by yarneo** [comment]
Yeah definitely. A workaround you can currently do due to the recent changes in this PR: https://github.com/material-components/material-components-ios/pull/4486/files#diff-77da929d5c751c28c35ac1925873b6b3 is listen to the newly added `state` property of `MDCBottomSheetController`. The state will change between `MDCSheetStateClosed`, `MDCSheetStatePreferred` and `MDCSheetStateExtended`. You can get more info about each of those states here: https://github.com/material-components/material-components-ios/blob/develop/components/BottomSheet/src/MDCSheetState.h

**Comment by material-mirror** [comment]
The internal issue [b/117177517](http://b/117177517) is now closed. This issue is being closed as a result.
