### ISSUE TITLE
[Tabs] MDCTabBar truncates badge value at 3 characters even though MDCItemBarCell claims it allows 3 characters

### ISSUE THREAD

**Issue by rajpara** [material-components/material-components-ios#4587]
## Description
When using a MDCTabBar as the bottom navigation bar, giving a tab bar item a badge value that is 3 characters or greater leads to truncation. So for example, a badge value of '30' shows up fine but a value of '303' would show up as '3...'.

Note that this is odd because MDCItemBarCell https://github.com/material-components/material-components-ios/blob/72045ffd6d303bb99a3e1a71e4f3cdda42fe5ad8/components/Tabs/src/private/MDCItemBarCell.m#L38 specifically calls out that 3 characters should be allowed.

## Reproduction steps

1. Go to BottomNavigationBarExample class where UITabBarItems are created https://github.com/material-components/material-components-ios/blob/3e441f22991368e1ceb3e3e130b0cb666b610b6f/components/Tabs/examples/BottomNavigationBarExample.m#L54
2. Modify the code to look like below so that we give an item a badge value

```
  UIImage *starImage =
      [UIImage imageNamed:@"TabBarDemo_ic_star" inBundle:bundle compatibleWithTraitCollection:nil];
  UITabBarItem *item = [[UITabBarItem alloc] initWithTitle:@"Red" image:infoImage tag:0];
    item.badgeValue = @"303";
  _bottomNavigationBar.items = @[
    item,
    [[UITabBarItem alloc] initWithTitle:@"Blue" image:starImage tag:0]
  ];
```
3. Run the MDCDragons app, go to Tab Bar -> Bottom Navigation

## Expected behavior

The badge value of 303 is shown without truncation

## Actual behavior

The badge value is truncated and shown as '3..'

## Platform (please complete the following information)

 - Device: iPhone 7 (11.4) Simulator

<img width="266" alt="screen shot 2018-07-17 at 3 40 18 pm" src="https://user-images.githubusercontent.com/41023534/42849353-bcb39824-89d7-11e8-8fcb-c11a8668da56.png">

---
#### Internal data
- Associated internal bug: [b/117177796](http://b/117177796)

**Comment by romoore** [comment]
MDCTabBar should not be used for Bottom Navigation. There is a dedicated component available in MDCBottomNavigationBar.  The UIViewController (MDCBottomNavigationController) is currently in [Beta availability](https://github.com/material-components/material-components-ios/blob/develop/contributing/beta_components.md) due to its active development.

Clients should migrate to MDCBottomNavigationBar as soon as possible. Once the controller is generally available, MDCTabBarController (and "bottom tabs") will be scheduled for deprecation.
