### ISSUE TITLE
[Dialogs] MDCAlertController documentation isn't in sync with the implementation

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#4621]
The documentation for MDCAlertController states actions should be added with affirmative actions first and dismissive actions second documentation - this suggests that actions will be laid out from top to bottom, which matches the material spec.
We are intentionally ordering from bottom to top to match UIAlertController.
This behavior should be documented.

---
#### Internal data
- Associated internal bug: [b/117178171](http://b/117178171)

**Comment by romoore** [comment]
Do we have a platform adaptation exception documented for this behavior?  If not, can we start the process to document this exception?

> Stacked buttons accommodate longer button text. Confirming actions appear above dismissive actions.
> —https://material.io/design/components/dialogs.html#anatomy

**Comment by romoore** [comment]
It looks like MDCAlertController is laying-out actions exactly opposite the way UIAlertController does.  Specifically, MDCAlertController lays-out bottom-to-top (vertical) and trailing-to-leading (horizontal). UIAlertController (generally) lays-out top-to-bottom (vertical) and leading-to-trailing (horizontal). 

Horizontally, MDCAlertController is conforming to the Material guidelines as long as programmers are adding "confirming" actions before "dismissive" actions.  Vertically, however, MDCAlertController should change to laying out actions in a top-to-bottom approach rather than bottom-to-top.  

**We should change the vertical layout to be consistent with both Material guidelines and UIAlertController behavior.**  It will be a breaking change. However, since MDCAlertController only uses vertical layout when there is no longer sufficient horizontal space for the actions, the user-facing changes should be relatively few.

----

UIKit seems to follow the layout rules below:

1. A `.cancel` action always goes on the leading/bottom edge. 
2. `.destructive` and `.default` actions are laid-out top-to-bottom or leading-to-trailing in the order they are added.

| Horizontal | Veritical|
|---|---|
|![uialert-horizontal](https://user-images.githubusercontent.com/1753199/43461004-50ee3828-94a0-11e8-9c1e-79e99bb5b848.gif)|![uialert-vertical](https://user-images.githubusercontent.com/1753199/43460906-01ebfe18-94a0-11e8-81cc-f81ef55178c6.gif)|

MDCAlert uses lays out all actions in bottom-to-top or leading-to-trailing in the order they are added.

|Horizontal | Veritical|
|---|---|
|![mdcalert-horizontal](https://user-images.githubusercontent.com/1753199/43462169-5f152904-94a3-11e8-85cf-38b222c3def1.gif)|![mdclaert-vertical](https://user-images.githubusercontent.com/1753199/43462173-635fdb58-94a3-11e8-94b5-49e587652f54.gif)|

**Comment by ianegordon** [comment]
We should be matching the Material guidelines.

This should e a simple fix of reversing the order when the buttons are laid out in a vertical manner.

**Comment by jverkoey** [comment]
Un-assigning due to inactivity. Please re-assign if you are working on this.

**Comment by romoore** [comment]
@galiak11 I believe this came-up in your work on an internal Dialogs migration.

**Comment by material-mirror** [comment]
The internal issue [b/117178171](http://b/117178171) is now closed. This issue is being closed as a result.
