### ISSUE TITLE
[Tabs] MDCTabBarViewController MDCTabBar position should be allowed to be set by the user

### ISSUE THREAD

**Issue by pikaboo** [material-components/material-components-ios#5294]
> For usage questions: ask on [Stack  Overflow](https://stackoverflow.com/questions/tagged/material-components+ios).

The tab bar position is set by default to be at the bottom, even though every example i found shows it to be at the top.
There is a piece of code that forces it to be at the bottom, instead of using the UIBarPosition that the user gave in the method

`    override func position(for bar: UIBarPositioning) -> UIBarPosition {
        return .top
    }`

## Reproduction steps

Create an MDCTabBarViewController without using AppBar

Create MDCTabBarViewController without using AppBar,
override method 
`    override func position(for bar: UIBarPositioning) -> UIBarPosition {
        return .top
    }`

## Expected behavior
TabBar appears at the top of the screen

## Actual behavior

AppBar appears at the bottom of the screen

A clear and concise description of what actually happened. Include screenshots or gifs where possible.
<img width="377" alt="tabbar" src="https://user-images.githubusercontent.com/3405551/46348915-3c3fc000-c659-11e8-800a-12ce192b9e34.png">

## Platform (please complete the following information)

 - Device:All devices
 - OS: All Os'

## Additional context
The problem lies here:

<img width="794" alt="updatelayout" src="https://user-images.githubusercontent.com/3405551/46348922-4366ce00-c659-11e8-9473-b471e0d90ef5.png">

You should use the "set variable" of the user, and not automatically use "UIBarPositionBottom"

---
#### Internal data
- Associated internal bug: [b/117143473](http://b/117143473)

**Comment by beraybentesen** [comment]
Any progress about this problem ?

**Comment by miguel-jimenez-0529** [comment]
Any updates about this?

**Comment by romoore** [comment]
I'm sorry if there's been any confusion, but MDCTabBarViewController is not meant to manage an MDCTabBar for anything other than bottom tabs. The original implementation of Tabs attempted to act as both Material Tabs and Material Bottom Navigation.  Due to the complex implementation details of Tabs, we are unable to actively maintain both styles of Tabs for new feature development.  Instead, we recommend using the dedicated Bottom Navigation component.

From [the MDCTabBarViewController header documentation](https://github.com/material-components/material-components-ios/blob/2803125b2c6457bb723ea56455da570e459d6dd5/components/Tabs/src/MDCTabBarViewController.h#L25):
> The MDCTabBarViewController class manages a set of view controllers, showing their UITabBarItems as tappable items **in a bottom MDCTabBar**. When the user taps one of those items, the corresponding view controller appears. *(Emphasis added)*
