### ISSUE TITLE
[Button] Can I change the corner radius of MDCContainedButtonThemer in Swift?

### ISSUE THREAD

**Issue by seongminchoob** [material-components/material-components-ios#5537]
## Additional context

<img width="322" alt="screen shot 2018-10-26 at 9 56 50 am" src="https://user-images.githubusercontent.com/35505959/47538284-7b35fe00-d905-11e8-8de6-31583a77863b.png">

Hello I'm using MDCContainedButtonThemer of 'MaterialComponents/Buttons'. 

I adopted MDCContainedButtonThemer and I want their corner radius to be 0 but changing the corner radius of buttons does not seem to fix the problem.

Is there any way I can make these buttons square? 
Thank you!

---
#### Internal data
- Associated internal bug: [b/118482172](http://b/118482172)

**Comment by codeman7** [comment]
Hello seongminchoob, thank you for using MDC components!

In order to set the cornerRadius for a MDCButton in Swift you'll need to set the _smallComponentShape_ for your _shapeScheme_ that the _buttonScheme_ uses. @yarneo and I will look into a better solution for this but as for now you'll need to do [this](https://gist.github.com/codeman7/e77dbceaca2c30a7bb6c0560baf6ab9d). We apologize for any confusion this may have caused for you.

**Comment by romoore** [comment]
@codeman7 It looks like our themer is still setting the `cornerRadius` on the layer. Is this no longer required?  Maybe a missing step in the shape themer?

https://github.com/material-components/material-components-ios/blob/develop/components/Buttons/src/ButtonThemer/MDCContainedButtonThemer.m#L29

**Comment by codeman7** [comment]
@romoore When we apply the shape [theme](https://github.com/material-components/material-components-ios/blob/07ed3771dc34de4806b62db187e68b669bbcfa2b/components/Buttons/src/ButtonThemer/MDCContainedButtonThemer.m#L26) it applies a [shapeGenerator](https://github.com/material-components/material-components-ios/blob/07ed3771dc34de4806b62db187e68b669bbcfa2b/components/Buttons/src/ShapeThemer/MDCButtonShapeThemer.m#L26). When we apply a shapeGenerator it overrides the [layer](https://github.com/material-components/material-components-ios/blob/07ed3771dc34de4806b62db187e68b669bbcfa2b/components/Buttons/src/MDCButton.m#L808-L823), and I don't believe [MDCShapedShadowLayer](https://github.com/material-components/material-components-ios/blob/develop/components/private/Shapes/src/MDCShapedShadowLayer.m) responds to cornerRadius  changes, so that [line](https://github.com/material-components/material-components-ios/blob/07ed3771dc34de4806b62db187e68b669bbcfa2b/components/Buttons/src/ButtonThemer/MDCContainedButtonThemer.m#L29) can be removed or we need to respond to cornerRadius changes in MDCShapedShadowLayer.

**Comment by romoore** [comment]
@codeman7 Can you please clarify the next steps/acceptance criteria for this issue? Are there changes to MDCButton or its theming code that needs to change?

**Comment by codeman7** [comment]
Hey @seongminchoob I hope my previous comments helped you understand how to get around this for custom `cornerRadius` on a `MDCContainedButtonThemer` if you have more questions about this please re-open the issue.
