### ISSUE TITLE
[TextFields] Dense Textfield support

### ISSUE THREAD

**Issue by material-mirror** [material-components/material-components-ios#5714]
This was filed as an internal issue. If you are a Googler, please visit [b/119249681](http://b/119249681) for more details.

---
#### Internal data
- Associated internal bug: [b/119249681](http://b/119249681)

**Comment by jverkoey** [comment]
This was mis-filed to us.

**Comment by J-Swift** [comment]
Hi @jverkoey I just came across this issue when looking up how to configure a TextField with 'dense' support (as described [in the spec](https://material.io/design/components/text-fields.html#outlined-text-field)). I didn't see any support for it in the current API, so I was wondering why this issue was closed originally.

Or I guess my real question is, how do I configure a TextField to be dense? : )

Thanks for all the work you guys do on this project, it really simplifies application of Material across platforms.

**Comment by adamteale** [comment]
HI @J-Swift, did you manage to figure out how to achieve this?

**Comment by J-Swift** [comment]
@adamteale - Honestly I don't remember, I left that job a couple months ago. We were originally using the 'legacy' field styling, so that might have been part of my issue. We eventually moved to the 'modern' outlined styling. I don't know if I was able to then add dense styling with the new style or not. 

Sorry I can't be more helpful : (

**Comment by adamteale** [comment]
@J-Swift thanks for letting me know anyway!
