### ISSUE TITLE
[Tabs] TabBarController does not support top tab bars

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#6929]
Although the Tabs component is intended to support both top and bottom tabs, our controller only supports bottom tabs.

Fix tab controller to support both top and bottom tabs.

A proposed fix can be seen in origin/tabbarcontrollerexample

@stefanamiller has further details about the use case.

---
#### Internal data
- Associated internal bug: [b/128853022](http://b/128853022)

**Comment by romoore** [comment]
Let's also consider a new VC that ONLY supports Material Tabs. "bottom tabs" functionality was replaced by Bottom Navigation.

**Comment by stefanamiller** [comment]
I have a need to embed some 'primary' tabs inside a view controller that is itself below some BottomNavigation tabs at the root of the app.

Would it also be possible to consider animations depending on the tab bar style so that that primary tabs animate alongside the slide of the underline when they are changing selection? This way the transition between view controllers and selection matches. This differs from the current MDCTabBarViewController, which [simply transitions without animation](https://github.com/material-components/material-components-ios/blob/c4d823362e016061725dc5ebdf5b4a4970aaa6b0/components/Tabs/src/MDCTabBarViewController.m#L215) as per this example:

![top-tabbarviewcontroller-example](https://user-images.githubusercontent.com/1054964/54556227-a7662000-4975-11e9-840b-d670a8934b85.gif) 

Aside: @romoore Is Bottom Navigation still in Beta? I see the BUILD target is "BottomNavigationBeta". So would it be more accurate to say "…'bottom tabs' functionality will be replaced by Bottom Navigation in the near future"?

**Comment by romoore** [comment]
@stefanamiller `MDCBottomNavigationBarController` is in Beta (pending some planned layout changes). However, `MDCBottomNavigationBar` is published in the CocoaPods podspec and is  generally available for use.

**Comment by hamada147** [comment]
It has been over a year on this bug, any update?

**Comment by RoqueCampos** [comment]
I'm interested too in a solution for this bug. Please, don't forget it

**Comment by andrewoverton** [comment]
I think the `MDCTabBarView` would meet your needs. It's most likely going to replace `MDCTabBarController`. It's currently in our [MaterialComponentsBeta](https://github.com/material-components/material-components-ios/blob/develop/MaterialComponentsBeta.podspec#L73) podspec, which we are working on deleting. You could try using it through that until we move it over to the MaterialComponents podspec. Hope this helps!

**Comment by danielkap** [comment]
Is there any news on this?

**Comment by andrewoverton** [comment]
Update from my last comment: MaterialComponentsBeta has been deleted, but `MDCTabBarView` has not been. That's what I would recommend everyone use. It acts as a top tab bar. See installation instructions [here](https://github.com/material-components/material-components-ios/blob/develop/components/Tabs/README.md#installing-tabs).

I'm going to preemptively close this issue, but feel free to re-open if necessary!
