### ISSUE TITLE
[Tabs] Tabs should be backed with an MDCShadowLayer

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#6930]
Right now our tab controller uses an internal MDCTabBarShadowView to allow elevation / shadow changes.

This could be simplified by back MDCTabBar with an MDCShadowLayer.

@stefanamiller has further details about the use case.

---
#### Internal data
- Associated internal bug: [b/128852860](http://b/128852860)

**Comment by stefanamiller** [comment]
This is to support tabs that are non-nested near the top of the screen, with content that scrolls up behind them. The shadow appears above this content from below the tab bar. 

Currently I have had to add my own MDCShadowLayer by subclassing the MDCTabBar and adding it as a sublayer, then updating its frame and laying-out when needed. e.g.:
``
- (void)layoutSublayersOfLayer:(CALayer *)layer {
  if (layer == self.layer) {
    _shadowLayer.frame = self.layer.bounds;
    [_shadowLayer layoutSublayers];
  }
}
``

**Comment by romoore** [comment]
I don't believe Material Tabs have shadows/elevation. However, when embedded in a Top App Bar, there would certainly be a shadow as content scrolls under the App Bar.   This issue was also discussed briefly in https://github.com/material-components/material-components-ios/pull/6449. 

Can you use an AppBar and assign an MDCTabBar for `appBarController.headerStackView.bottomBar`?  I believe that would be the expected way to have Tabs as part of an App Bar and have content scroll beneath it.

**Comment by stefanamiller** [comment]
Thanks for the suggestion @romoore. I gave that a try and while it works, my UX designer and PM both agree that the tabs need to stay onscreen when the app bar shifts away. This makes sense because the two tabs I have are similar in content and keeping the tab context on-screen at the top makes it clear which the user is looking at.

Aside: when implementing this, I had to manually set both `maximumHeight` an `minimumHeight` to include the height of my tab bar. This seems a bit unusual given that it is being placed in a UIStackView that is based around AutoLayout. Given AutoLayout is in play, I'd expect the app bar to adjust height based on the intrinsicContentSize.height of the view I have set.

**Comment by romoore** [comment]
@stefanamiller  MDC doesn't make use of UIStackView (not yet). Do you mean it's odd because you are placing your Tab bar within a UIStackView and adding that to the Flexible Header or something else?

**Comment by romoore** [comment]
Notably, MDCHeaderStackView has [some surprising behavior when it comes to `sizeThatFits:`](https://raw.githubusercontent.com/material-components/material-components-ios/2181084/components/HeaderStackView/src/MDCHeaderStackView.h). I'm not sure exactly why it does that, but I did notice it recently when I was adding snapshot tests to the component.

**Comment by romoore** [comment]
I'm going to close this Issue since Tabs should not have shadows/elevation directly.  Please feel free to open an Issue into HeaderStackView (or probably more meaningfully against AppBar) detailing the challenges you've had trying to get your layout to work.

**Comment by stefanamiller** [comment]
> @stefanamiller MDC doesn't make use of UIStackView (not yet). Do you mean it's odd because you are placing your Tab bar within a UIStackView and adding that to the Flexible Header or something else?

Ah, I missed that `appBarController.headerStackView` is an MDCHeaderStackView instead of a UIStackView. I meant it would be odd because of how UIStackView and AutoLayout system works. But, since `MDCHeaderStackView` uses `sizeThatFits:` I understand why the height has to be adjusted manually.
