### ISSUE TITLE
Bazel can't build our projects without being invoked from .kokoro

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#6956]
If I run bazel build //catalog:MDCCatalog in the root directory I would expect it to build our catalog.

It does not work unless you invoke bazel through the .kokoro script.

This is surprising.

Consider fixing the BUILD files to work as expected OR prefix them with a big WARNING that they don't work out of the box.

---
#### Internal data
- Associated internal bug: [b/128997718](http://b/128997718)

**Comment by romoore** [comment]
Since kokoro + bazel is primarily meant as presubmit CI builds (faster than CocoaPods), it may be worth finding a better way to document the intended usage.  Currently, it's only in a `contributing` directory.  Perhaps the comment at the top of the BUILD files could include a link to the instructions.

https://github.com/material-components/material-components-ios/blob/develop/contributing/bazel_kokoro.md#running-kokoro-presubmits-locally

**Comment by romoore** [comment]
Closing this since this is intended.
