### ISSUE TITLE
List's layout is broken in its snapshot test.

### ISSUE THREAD

**Issue by wenyuzhang666** [material-components/material-components-ios#7487]
List's layout is broken in its snapshot test.

**Comment by romoore** [comment]
@wenyuzhang666 Please clarify how this can be done. I called both `intrinsicContentSize` and `sizeThatFits:` and neither returned the size the List item requires to fully display its content.

**Comment by wenyuzhang666** [comment]
This issue was filed for finding a way to support Autolayout in tests. I saw `systemLayoutSizeFittingSize` was implemented, so I think using a full Autolayout environment will make the List item's size work in tests.

**Comment by romoore** [comment]
`systemLayoutSizeFittingSize` may be part of that work, but there should also be a way to determine how big the cell desires to be. Even if the cell only sizes its height (given a width), that's fine. It appears that the List is broken with respect to its layout. Since this Issue implies that the test can be updated to correct the layout, I'm asking you to clarify those steps. This is not actionable as it stands, so I would like help understanding what is necessary to complete this work.

**Comment by wenyuzhang666** [comment]
I changed the title to the layout is broken as you mentioned in the original PR. Can you help to fill in what do you feel is broken in the layout, and what needs to be solved?
