### ISSUE TITLE
React to Swift Package Manager - Internal issue: b/135017130

### ISSUE THREAD

**Issue by material-mirror** [material-components/material-components-ios#7559]
This was filed as an internal issue. If you are a Googler, please visit [b/135017130](http://b/135017130) for more details.

---
#### Internal data
- Associated internal bug: [b/135017130](http://b/135017130)
- Blocked by: https://github.com/material-components/material-components-ios/issues/8433

**Comment by artemisia-absynthium** [comment]
As told in https://github.com/material-components/material-components-ios/issues/3207#issuecomment-570304583, I’m bumping this issue to raise its visibility to your team! Thank you very much ☺️

**Comment by jaerod95** [comment]
Would love to see this or Accio Support at the least

**Comment by reshadf** [comment]
Would love to see support soon!

**Comment by Bernix01** [comment]
Would love to see support soon!

**Comment by Bernix01** [comment]
Recently started a project and tried to use SPM and this library, MaterialTextFields to be specific. So I played around with the files and the `Package.swift` and got it working! (Just Textfields at this time, which is what I need). Maybe it's not the best way to achieve it but for sure might help you in your investigation and maybe hint a way of achieving this.

[The repo](https://github.com/grupopulpo/material-components-ios)

**Comment by trapper-** [comment]
Would love to see this, please :)

**Comment by DomenicBianchi01** [comment]
@jverkoey Any updates on this? Of all the third-party libraries my company uses, this is the last one to not support it. It would be awesome if SPM can be added to this project. :)

**Comment by joaoduartemariucio** [comment]
@jverkoey Any updates on this? I find myself in the same situation as @DomenicBianchi01

**Comment by DomenicBianchi01** [comment]
@andrewoverton Tagging you since you seem to be active (handled the past couple of releases). Even if someone could provide an ETA on when SPM could be added to this project that would be super helpful!

**Comment by koraykoska** [comment]
+1

**Comment by DomenicBianchi01** [comment]
@andrewoverton Could you please let us know if there are any plans to support SPM? If there is not, please let us know.

**Comment by andrewoverton** [comment]
Hi everyone, apologies for the radio silence so far on this issue. I don't believe we have any immediate plans to support Swift Package Manager. That could change, but so far I haven't heard it discussed very much within the team.

**Comment by backslash-f** [comment]
That's really going into the opposite direction of modern Swift / iOS development. All other major third-party libraries have already migrated to SPM. I kindly ask the development team to reconsider it. Please. 🙏🏻

**Comment by lalkrishna** [comment]
It's already late. A repo that that only support cocapods? Wah 👎 . Please Add Support ASAP

**Comment by varahash** [comment]
@andrewoverton Are you open for PRs from the community?

**Comment by nastasiupta** [comment]
any update regarding SPM support :) ?

**Comment by DomenicBianchi01** [comment]
Is there really no plan to add SPM to this project??? Almost thinking it's gonna be worth it to start looking at other repos or build out some UI components manually. :(

**Comment by that-scalcucci-guy** [comment]
Would just like to add to the list of developers that think it's a bit ridiculous this hasn't been done yet. This is one of the last major libraries that have yet to add SPM support.

The process takes very little effort. Instead, we're forced to fork and implement it ourselves.

**Comment by jverkoey** [comment]
We are happy to accept PRs. I appreciate and understand the frustration felt here, and we're very open to accepting community contributions to help move this forward.

**Comment by DomenicBianchi01** [comment]
@jverkoey I'm gonna start tackling some of the components I need for my project and hopefully once I get the ball rolling...others will help chip in as well.

I'm going to start with Text Fields and as such need to add SPM to some dependencies. My first PR is here: https://github.com/material-foundation/material-text-accessibility-ios/pull/36

I have left 2 questions there since I wasn't sure what was happening (tbh I'm not super proficient with Objective-C stuff) but I'm wondering if the issues I ran into are simply because the project hasn't been updated in a long time and the compiler/cocoapods has just changed.

**Comment by DomenicBianchi01** [comment]
@jverkoey Also, please let me know if there is a better way to notify you or anyone else that would be able to review this PR's!

**Comment by andrewoverton** [comment]
I'm a little concerned about external people (non-Googlers) attempting this work because they don't have visibility into how all our stuff is used internally. It'd definitely be possible for someone who doesn't have access to the internal mono-repo to make SPM work from the CocoaPods/GitHub perspective, but if it breaks stuff _internally_ that seems like it may be a no-go.

@DomenicBianchi01, I see that with https://github.com/material-foundation/material-text-accessibility-ios/pull/36 you change the folder structure from "src" to "Sources," because "Sources" is the SPM convention. Changing the folder structure may not be an issue with the text accessibility library, since it may not have any internal usage outside of MDC (I haven't checked), but doing the same thing with MDC could be more of an issue, since MDC files get imported a lot internally. A lot of the import statements throughout Google's suite of apps would have to change too if we restructured everything in MDC to be under "Sources" directories. This could still be the way to go, but it's not what I was going to try first. I was going to attempt to make it work leaving the folder structure largely intact. If I understand correctly, that would require using [this initializer](https://developer.apple.com/documentation/swift_packages/target/3583314-target?language=objc) to specify that all the sources live under "src" instead of "Sources." 

@jverkoey Do you have any thoughts about this?

**Comment by jverkoey** [comment]
The `src/` convention we use is consistently applied across all products our team owns, so we are unlikely to change that.

Swift package manager provides a `path` argument that can be used to change the name of the default location for source:

From https://docs.swift.org/package-manager/PackageDescription/PackageDescription.html#id5:

`///   - path: The custom path for the target. By default, targets will be looked up in the <package-root>/Sources/<target-name> directory.`

Consider setting `path: "src/"`.

**Comment by DomenicBianchi01** [comment]
I tried setting the path but SPM wasn't picking up the directory for some reason. Sounds like having external people work on SPM is gonna be too risky if we don't know what will break internal Google tools.

**Comment by jverkoey** [comment]
I've used `path` in separate projects before. It is finicky, but it does work (e.g. https://github.com/jverkoey/windfish/blob/develop/third_party/Package.swift#L18-L23). May need to check things like trailing slashes.

I believe it should be possible to support Swift Package Manager without having to significantly adjust our conventions and I'm supportive of this. We'll def let y'all know if/when something is very meaningfully going to affect code internal to Google, but I don't think we've hit a wall yet.

**Comment by DomenicBianchi01** [comment]
I'll give it another shot in a bit...this time without modifying the file structure.

**Comment by DomenicBianchi01** [comment]
@jverkoey Got it working! https://github.com/material-foundation/material-text-accessibility-ios/pull/37

There are no changes to Cocoapods or the file structure so this PR is definitely way better than the other one I had lol.

**Comment by jverkoey** [comment]
Nice one! @andrewoverton can you help get the PR reviewed + landed?

**Comment by andrewoverton** [comment]
material-foundation/material-text-accessibility-ios#37 seems to work! And yep 👍

**Comment by DomenicBianchi01** [comment]
@jverkoey @andrewoverton PR for internationalization: https://github.com/material-foundation/material-internationalization-ios/pull/59.

**Comment by andrewoverton** [comment]
Will land tomorrow and in coming days! Thanks again @DomenicBianchi01

**Comment by haemi** [comment]
any updates on this? 🙂

**Comment by DomenicBianchi01** [comment]
@haemi I'm slowly working on it but have higher priorities (only working on it when I have free time really). We ran into some Cocoapods compatibility issues a couple weeks ago with some dependencies but we've resolved them so I'm just waiting for those changes to get approved and merge in...then I'll start working on actually getting SPM support for this repo.

**Comment by andrewoverton** [comment]
There are some internal updates that I need to do before we can land https://github.com/material-foundation/material-text-accessibility-ios/pull/37 and https://github.com/material-foundation/material-internationalization-ios/pull/59. Once those PRs land, I think we should be able to expand SPM to the components in this library fairly quickly. Sorry for the wait everyone!

**Comment by yanniks** [comment]
@andrewoverton any update on this?

**Comment by federicopolesello** [comment]
+1

**Comment by AshStefanOltmann** [comment]
+1

**Comment by glaurent** [comment]
+1

**Comment by quentinSquad** [comment]
+1

**Comment by jverkoey** [comment]
Hey gang,

As of July 15th, all of the iOS libraries for Material have entered maintenance mode. See more details at https://github.com/material-components/material-components-ios#materials-ios-libraries-are-in-maintenance-mode-as-of-july-15-2021

We accordingly will not be pursuing Swift package manager support.
