### ISSUE TITLE
[MDCCatalog] Self-Sizing UICollectionViewCell in Vertical Flow Layout with Animations.

### ISSUE THREAD

**Issue by yakushevichsv** [material-components/material-components-ios#7973]
## Feature Request/Suggestion

[MDCCatalog] Self-Sizing UICollectionViewCells in Vertical Flow Layout with Animations.

## Additional context

Sorry, I am struggling with the self-sizing collection view cells. 
I mean I would like to animate  row/section, headers appearance(disappearance), insertion(deletion) using derivative from `UICollectionViewFlowLayout` class & cells' which are adjusted due to auto layout.

You can check my relative question at [stackoverflow](https://stackoverflow.com/questions/57133350/cells-animation-in-vertical-uicollectionviewflowlayout-with-self-sized-cells-do). 
 
I see that there is `MDCCollectionViewFlowLayout` which implements "similar" logic, but I can't locate an example how to use it, even in `MDCCatalog` sample app.

Self sizing is done in 'MDCSelfSizingStereoCell'

Could you please point me at the proper sample code, or place how use, test MDCCollectionViewFlowLayout or/and MDCSelfSizingStereoCell?

Perhaps you can point me at how to properly animate items in `UICollectionViewFlowLayout`?

  

---
#### Internal data
- Associated internal bug: [b/138619707](http://b/138619707)

**Comment by andrewoverton** [comment]
H @yakushevichsv,

MDCCollectionViewFlowLayout is part of our Collections component, and MDCSelfSizingStereoCell is part of our List component. They are different solutions. I can't speak to whether or not their use _together_ is possible, but I can tell you it is not supported.

While not officially deprecated, MDCCollections have been de-prioritized. Some of the criticisms of MDCCollections have revolved around the fact that their large number of moving parts gave them a high cost of adoption with little flexibility in return. Lists were intended as a lightweight alternative. The idea behind the List component is that instead of supplying our own MDC prefixed object for every element in the UICollectionView object graph we should just provide cells that do one thing, and let clients write their own collection view code around them. MDCSelfSizingStereoCell is the first one of these cells.

If the MDCSelfSizingStereoCell--with its two labels and image views--meets your needs, I'd recommend using it, and writing the cell display animations yourself, just as you would with a regular UICollectionView. Otherwise, I'd encourage you to see some of the MDCCollections documentation, which can be found in the following READMEs:

https://github.com/material-components/material-components-ios/blob/develop/components/Collections/README.md
https://github.com/material-components/material-components-ios/blob/develop/components/CollectionCells/README.md
https://github.com/material-components/material-components-ios/blob/develop/components/CollectionLayoutAttributes/README.md

**Comment by yakushevichsv** [comment]
@andrewoverton Thank you.
I got your point. Really great documentation. 
There is an example of how to use `MDCCollectionViewFlowLayout`, isn't it?

**Comment by yakushevichsv** [comment]
MDCCollectionViewFlowLayout is referenced by CollectionsStoryboardExample.storyboard, I just can't locate an easy path how to activate it.
