### ISSUE TITLE
[ActivityIndicator] Unit test fails on iOS 13.

### ISSUE THREAD

**Issue by wenyuzhang666** [material-components/material-components-ios#8239]
Add `ci_mode=autobot` in `.kokoro` above `bazel $COMMAND $TARGET --xcode_version $xcode_version --ios_minimum_os=9.0` in `run_bazel()` to reproduce.

Error occurs when testing using Bazel.
```
Test Case '-[components_ActivityIndicator_unit_test_swift_sources.ActivityIndicatorColorThemerTests testColorThemerChangesTheBackgroundColor]' started.
Child process terminated with signal 11: Segmentation fault
```

---
#### Internal data
- Associated internal bug: [b/139096168](http://b/139096168)

**Comment by romoore** [comment]
@wenyuzhang666 Could you please document which Xcode 11 beta is producing this error?

**Comment by jverkoey** [comment]
It's concerning that Swift tests would be segfaulting with such a simple test. Are you able to reproduce this segfault directly in any manner?

**Comment by acecilia** [comment]
Hi @wenyuzhang666 and @jverkoey 👋 Could you talk a bit about the root cause of this issue?

Was this a Bazel bug?
Was this an xcode bug?
Was it something else?

I am currently experiencing this issue sometimes (flaky test), and this ticket is one of the only ones I found mentioning that bazel/xcode could be the root cause.

Thanks!
