### ISSUE TITLE
unable to change font

### ISSUE THREAD

**Issue by KaitieKirchner** [material-components/material-components-ios#8795]
### Overview
For usage questions: ask on [Stack  Overflow](https://stackoverflow.com/questions/tagged/material-components+ios).

 - Context, problem or idea, solution or next step
 - Screenshots/Video (if possible)
 - Stack trace (if possible)

### Reproduction steps
 - click on font dropdown in material editor - dropdown does not work.

### Version number
 - Found in CHANGELOG.md

### Operating system and device
mac 10.14.6
### Related issues
 - Type `#` and the issue number or `#` and select the from the inline drop down.

**Comment by romoore** [comment]
Hi @KaitieKirchner . I'm closing this issue because I believe you might have filed this issue in the wrong repository. Material iOS Components do not support macOS and we don't have a "material editor."  Sorry for any confusion!

If you are having difficulties with a specific tool or piece of software, I would recommend checking either the site you purchased/downloaded it or the "Help" menu for determining how to contact the authors.
