### ISSUE TITLE
Update CocoPods support to 1.8.x

### ISSUE THREAD

**Issue by material-mirror** [material-components/material-components-ios#8997]
This was filed as an internal issue. If you are a Googler, please visit [b/144767641](http://b/144767641) for more details.

The internal bug was opened due to https://github.com/material-components/material-components-ios/issues/8987

---
#### Internal data
- Associated internal bug: [b/144767641](http://b/144767641)

**Comment by yarneo** [comment]
I've tested using a demo app that installs our library via CoacoaPods 1.8.4 with no failures.

I have also imitated the client's actions of choosing to install chips specifically:
```
 use_frameworks!
 pod 'MaterialComponents/Chips'
```

And then ran it on my iPhone 11 iOS 13.2.3 and had no errors.

I believe based on this that the issue is most likely to do with a set up with the client's workspace, and not to do with issues integrating our components using CocoaPods 1.8.x
