### ISSUE TITLE
[TextControls] Expose a mechanism for density on textfields

### ISSUE THREAD

**Issue by material-mirror** [material-components/material-components-ios#9324]
This issue was created in response to this MDCTextField question: https://github.com/material-components/material-components-ios/issues/9291

Acceptance criteria:
MDCTextControl textfields expose a mechanism to adjust density.

---
#### Internal data
- Associated internal bug: [b/146642024](http://b/146642024)

**Comment by Fernandez-Aldo** [comment]
Are there any updates for this issue?

**Comment by andrewoverton** [comment]
Density was brought up again in https://github.com/material-components/material-components-ios/issues/9860. I really think we should expose it soon! If any of you want to vote for how it should work, please do so on [this comment](https://github.com/material-components/material-components-ios/issues/9860#issuecomment-596766079). Since I just put the poll there I'm going to use that issue for the density stuff from now on and close this one, just so there aren't duplicates. Sorry for the wait on density :/
