### ISSUE TITLE
No such module 'MaterialComponents.MaterialNavigationDrawer_Theming'

### ISSUE THREAD

**Issue by bweston92** [material-components/material-components-ios#9998]
> For usage questions: ask on [Stack  Overflow](https://stackoverflow.com/questions/tagged/material-components+ios).

## Reproduction steps

1. Create new Swift Storyboard project
2. Add 'MaterialComponents' to Podfile
3. Run `pod install` `pod try MaterialComponents`
4. Choose option 1 `1: catalog/MDCCatalog.xcworkspace`
5. Try to run.

## Expected behaviour

Application is built and usable.

## Actual behaviour

Fails to compile.

`import MaterialComponents.MaterialNavigationDrawer_Theming` gives error `No such module 'MaterialComponents.MaterialNavigationDrawer_Theming'`

<img width="511" alt="Screenshot 2020-05-20 at 10 32 01" src="https://user-images.githubusercontent.com/1764057/82430440-39d7e700-9a85-11ea-939a-b2016eb10083.png">

## Additional context

I was following README.

**Comment by andrewoverton** [comment]
Hi @bweston92, Thanks for filing this issue. The `MaterialComponentsExamples` target was broken at the commit the last release was cut from. I guess this has ramifications for `pod try`. You should be able to get rid of these compiler errors by commenting out one-by-one the lines that cause compilation to fail. There are just a few, it shouldn't take long. You could just comment out that whole file actually and that'd work too.

Note that `MaterialComponents` builds fine in the latest release, so if you wanted to check out the library another way you could add it to a Podfile and run pod install. Or if you wanted to clone the repo and just work off the `develop` branch that should work too. Sorry for the inconvenience! This issue with `pod try` will be fixed in the next release, which will land around next Tuesday.

**Comment by codeman7** [comment]
This was fixed in v109.5.0
